### PR TITLE
prefilter liwc_list for globs

### PR DESCRIPTION
**Pull request by jpfairbanks**
```
NEW

root@5ed1b79bf0e9:/src/bs_detector# time python bias.py
0.4571

real	0m11.338s
user	0m11.070s
sys	0m0.100s

OLD
root@5ed1b79bf0e9:/src/bs_detector# time python bias.py
0.4571

real	0m15.148s
user	0m14.800s
sys	0m0.130s
```

### CODE REVIEW

**Comment by jpfairbanks** [comment]
Second commit
```
root@5ed1b79bf0e9:/src/bs_detector# time python bias.py
0.4571

real	0m7.164s
user	0m6.830s
sys	0m0.120s```

50% speedup in less than an hour.

**Comment by jpfairbanks** [comment]
@cjhutto @scottagt can we merge this perf improvement too?

**Review by cjhutto — APPROVED** [review]

**Comment by scottagt** [comment]
So the prefilter thing I agree makes sense. For the set, why is changing the feat_list to a set better to do? If that's the case then maybe the feat_lists (all the liwc lists) should just be stored as frozen sets, right? And then no computations for making sets are added each time?

**Comment by jpfairbanks** [comment]
Yeah if those sets don't change at all during program operation then they should be converted to frozen sets. This change didn't really require me to think about the global behavior of the code. It was a quick win.

**Pull request merged**
